#ifndef CPSC131_DATABASES_DINOSAURS_DATALOADER_HPP
#define CPSC131_DATABASES_DINOSAURS_DATALOADER_HPP

/**
 * DO NOT EDIT THIS FILE
 */

#include <memory>
#include <random>
#include <sstream>
#include <string>
#include <vector>


#include "MyBST.hpp"
#include "DinosaurTypeDefs.hpp"
#include "Dinosaur.hpp"


//
namespace CPSC131::Databases::Dinosaurs
{
	//
	class DinoDataLoader
	{
		public:
			
			static constexpr const char * DEFAULT_DATA_FILENAME = "data.csv";
			static constexpr size_t BUFFER_SIZE = 16384;
			static constexpr size_t ITERATIONS_PER_DOT = 1000;
			
			DinoDataLoader();
			
			void loadDinosaursToTree(DinoTree& tree, size_t count, unsigned int seed = 0);
			
			std::unique_ptr<std::vector<Dinosaur>> loadCSV();
			
		private:
			
			std::random_device random_device_;
			std::default_random_engine rng_;
			
			std::string data_filename_ = DEFAULT_DATA_FILENAME;
			
			std::string loadCSVColumn(std::stringstream& ss, size_t index);
			
	};
}


#endif

