#ifndef CPSC131_DATABASES_DINOSAURS_TYPEDEFS_HPP
#define CPSC131_DATABASES_DINOSAURS_TYPEDEFS_HPP


/**
 * DO NOT EDIT THIS FILE
 */


#include "MyBST.hpp"


//
namespace CPSC131::Databases::Dinosaurs
{
	typedef BST::MyBST<class Dinosaur> DinoTree;
}


#endif
