
#########################
# DO NOT EDIT THIS FILE #
#########################

# But please, feel free to inspect the targets and design for your own learning.

define say
	$(info [MyBST] $1)
endef

#
CC        := g++
CFLAGS    := -Wall -Werror -pedantic -g -std=c++23 -c
LINKFLAGS := -Wall -Werror -pedantic -g -std=c++23


#
BIN_TUI_INTEGERS_NAME := main-integers
BIN_TUI_INTEGERS := ./$(BIN_TUI_INTEGERS_NAME)
#
BIN_TUI_DINOSAURS_NAME := main-dinosaurs
BIN_TUI_DINOSAURS := ./$(BIN_TUI_DINOSAURS_NAME)
#
BIN_SANDBOX_NAME := main-sandbox
BIN_SANDBOX := ./$(BIN_SANDBOX_NAME)
#
BIN_TESTS_NAME := main-tests
BIN_TESTS := ./$(BIN_TESTS_NAME)
#
BIN_LEAK_CHECKER_NAME := leak-checker
BIN_LEAK_CHECKER = ./$(BIN_LEAK_CHECKER_NAME)


#
DEPS_PUHP := $(wildcard puhp-tests/*)
DEPS_HELPERS := Renderer.hpp Randomer.hpp MyDinosaurDatabase.hpp Dinosaur.hpp DinoDataLoader.hpp


#
default:	help


#
help:
	@echo "***** Makefile Menu *****"
	@echo
	@echo "make build             ==> Build source files"
	@echo
	@echo "make run-integers      ==> Run the integers-based tui"
	@echo "make debug-integers    ==> Debug the integers-based tui with gdb"
	@echo
	@echo "make run-dinosaurs     ==> Run the dinosaurs-based tui"
	@echo "make debug-dinosaurs   ==> Debug the dinosaurs-based tui with gdb"
	@echo
	@echo "make sandbox           ==> Run the sandbox (sandbox.cpp)"
	@echo "make debug-sandbox     ==> Debug the sandbox program with gdb"
	@echo
	@echo "make test              ==> Run tests against your project"
	@echo "make debug-test        ==> Debug the tests run against your project"
	@echo
	@echo "make clean             ==> Clean temporary build files"


#
build:	$(BIN_TUI_INTEGERS) $(BIN_TUI_DINOSAURS) $(BIN_SANDBOX) $(BIN_TESTS)
.PHONY: build


#
run-integers:	$(BIN_TUI_INTEGERS)
	$(call say,Running the integers TUI)
	$(BIN_TUI_INTEGERS)
.PHONY: run-integers


#
run-dinosaurs:	$(BIN_TUI_DINOSAURS)
	$(call say,Running the dinosaurs TUI)
	$(BIN_TUI_DINOSAURS)
.PHONY: run-dinosaurs


#
sandbox:	$(BIN_SANDBOX)
	$(call say,Running the sandbox)
	$(BIN_SANDBOX)
.PHONY: sandbox


#
debug-sandbox:	$(BIN_SANDBOX)
	$(call say,Debugging the sandbox)
	gdb $(BIN_SANDBOX) -ex run
.PHONY: debug-sandbox


#
debug-integers:	$(BIN_TUI_INTEGERS)
	$(call say,Debugging the integers tui)
	gdb $(BIN_TUI_INTEGERS) -ex run
.PHONY: debug


#
debug-dinosaurs:	$(BIN_TUI_DINOSAURS)
	$(call say,Debugging the dinosaurs tui)
	gdb $(BIN_TUI_DINOSAURS) -ex run
.PHONY: debug-dinosaurs


#
gradescope:	clean
gradescope:	test
tests:		test
test:		$(BIN_TESTS)
	$(call say,Running tests)
	$(BIN_TESTS)
.PHONY: gradescope tests test


#
debug-tests:		debug-test
debug-test:	$(BIN_TESTS)
	$(call say,Debugging the tests)
	gdb $(BIN_TESTS) -ex run
.PHONY: debug-tests debug-test


#
$(BIN_TUI_INTEGERS):	main_integers.o
	$(call say,Linking: $@)
	$(CC) $(LINKFLAGS) $^ -o "$@"


#
$(BIN_TUI_DINOSAURS):	main_dinosaurs.o MyDinosaurDatabase.o DinoDataLoader.o Dinosaur.o
	$(call say,Linking: $@)
	$(CC) $(LINKFLAGS) $^ -o "$@"


#
$(BIN_SANDBOX):	sandbox.o DinoDataLoader.o Dinosaur.o
	$(call say,Linking: $@)
	$(CC) $(LINKFLAGS) $^ -o "$@"


#
$(BIN_TESTS):	CPP_Tests.o DinoDataLoader.o Dinosaur.o MyDinosaurDatabase.o
	$(call say,Linking: $@)
	$(CC) $(LINKFLAGS) $^ -o "$@"


# Link the leak checker binary
$(BIN_LEAK_CHECKER):	leak_checker.o
	$(call say,Linking: $@)
	$(CC) $(LINKFLAGS) leak_checker.o -o "$@"


#
main_integers.o:	main_integers.cpp MyBST.hpp $(DEPS_HELPERS)
	$(call say,Compiling: $@)
	$(CC) $(CFLAGS) "$<" -o "$@"


#
main_dinosaurs.o:	main_dinosaurs.cpp MyBST.hpp MyDinosaurDatabase.o Dinosaur.o DinoDataLoader.o $(DEPS_HELPERS)
	$(call say,Compiling: $@)
	$(CC) $(CFLAGS) "$<" -o "$@"


#
sandbox.o:	sandbox.cpp MyBST.hpp $(DEPS_HELPERS)
	$(call say,Compiling: $@)
	$(CC) $(CFLAGS) "$<" -o "$@"


#
MyDinosaurDatabase.o:	MyDinosaurDatabase.cpp MyDinosaurDatabase.hpp Dinosaur.o MyBST.hpp DinoDataLoader.hpp
	$(call say,Compiling: $@)
	$(CC) $(CFLAGS) "$<" -o "$@"


#
DinoDataLoader.o:	DinoDataLoader.cpp DinoDataLoader.hpp Dinosaur.o MyBST.hpp
	$(call say,Compiling: $@)
	$(CC) $(CFLAGS) "$<" -o "$@"


#
Dinosaur.o:	Dinosaur.cpp Dinosaur.hpp
	$(call say,Compiling: $@)
	$(CC) $(CFLAGS) "$<" -o "$@"


#
CPP_Tests.o:	CPP_Tests.cpp MyBST.hpp MyDinosaurDatabase.o Dinosaur.o $(DEPS_PUHP) $(DEPS_HELPERS)
	$(call say,Compiling: $@)
	$(CC) $(CFLAGS) "$<" -o "$@"


#
leak_checker.o:	leak_checker.cpp MyBST.hpp DinoDataLoader.hpp $(DEPS_HELPERS)
	$(call say,Compiling: $@)
	$(CC) $(CFLAGS) "$<" -o "$@"


#
clean:
	$(call say,Cleaning build area)
	-rm *.o
	-rm $(BIN_TUI_DINOSAURS)
	-rm $(BIN_TUI_INTEGERS)
	-rm $(BIN_TESTS)
	-rm $(BIN_SANDBOX)
	-rm $(BIN_LEAK_CHECKER_NAME)
	-rm results*.json
	-rm *.png
	-rm *.dot
.PHONY: clean









